In [1]:
# 경고무시
import warnings
warnings.filterwarnings(action='ignore', category=DeprecationWarning)

In [2]:
# load library
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib as mpl
mpl.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['font.size'] = 10

In [3]:
# load data
# 2021-01-01_2021-06-30
online_data = pd.read_csv("C:/nh/품종.csv")
online_data.head()

,상품카테고리(세),상품명,품종,무게,성별,나이,결제금액,결제수,결제상품수량,환불금액,환불건수,환불수량,실결제금액,실결제수량
0,백미,NH신동진쌀,신동진,10kg,남성,36~40,"274,200",5,8,0,0,0,274200,8
1,백미,NH신동진쌀,신동진,10kg,여성,36~40,"68,800",2,2,0,0,0,68800,2
2,백미,NH신동진쌀,신동진,10kg,여성,46~50,"68,800",2,2,0,0,0,68800,2
3,백미,NH신동진쌀,신동진,10kg,남성,41~45,"68,800",2,2,0,0,0,68800,2
4,백미,NH신동진쌀,신동진,10kg,남성,61~65,"68,800",2,2,0,0,0,68800,2

In [4]:
# 결측치 확인
online_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 873 entries, 0 to 872
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   상품카테고리(세)  873 non-null    object
 1   상품명        873 non-null    object
 2   품종         873 non-null    object
 3   무게         873 non-null    object
 4   성별         873 non-null    object
 5   나이         873 non-null    object
 6   결제금액       873 non-null    object
 7   결제수        873 non-null    int64
 8   결제상품수량     873 non-null    int64
 9   환불금액       873 non-null    object
 10  환불건수       873 non-null    int64
 11  환불수량       873 non-null    int64
 12  실결제금액      873 non-null    int64
 13  실결제수량      873 non-null    int64
dtypes: int64(6), object(8)
memory usage: 95.6+ KB

In [21]:
pd.set_option('display.max_rows', None)

In [24]:
# 품종별 나이대
grouped_name_s_r = online_data.groupby(['품종','나이'])['실결제금액'].sum()
grouped_name_s_r

품종     나이
고시히카리  20~25      445900
       26~30     1735400
       31~35     6060200
       36~40     6765700
       41~45     6814700
       46~50     3606500
       51~55     2830200
       56~60     2276500
       61~65      690500
       66~70       79900
       71+         83800
삼광     20~25      491300
       26~30     1008400
       31~35     1233700
       36~40     2646600
       41~45     2292700
       46~50     1944100
       51~55     1376600
       56~60      744300
       61~65      261000
       66~70      202500
새청무    20~25      120400
       26~30      839300
       31~35      361200
       36~40      120400
       41~45      177600
       46~50      601500
       51~55      120400
       56~60      361200
       61~65      301000
       66~70       60200
       71+         60200
신동진    20~25     1773600
       26~30     2973200
       31~35     5273700
       36~40     9240800
       41~45     7408000
       46~50     9458400
       51~55     4539300
       56~60     2008400
       61~65      751600
       66~70      405100
       71+        126800
십리향    20~25       88200
       26~30      538000
       31~35      731700
       36~40      728400
       41~45      507900
       46~50      486300
       51~55      834900
       56~60      263600
       61~65      133400
       71+         44100
영호진미   20~25      235000
       26~30      818900
       31~35     2397000
       36~40     2226000
       41~45     2430500
       46~50     1178500
       51~55      833500
       56~60      472000
       61~65      214500
       66~70       21000
       71+        264000
오대     26~30       60200
       31~35       60200
       36~40       58200
       41~45      239800
       46~50       80600
       56~60      166600
       61~65       19400
       66~70       43000
일미     26~30       34500
       31~35      149500
       36~40      689100
       41~45      210600
       46~50      180500
       51~55      238700
       56~60       66600
       61~65       72000
       66~70       66600
       71+        263900
일품     20~25      674400
       26~30     1188000
       31~35     1360900
       36~40     2538600
       41~45     3811900
       46~50     2350100
       51~55      849700
       56~60      856000
       61~65      356700
       66~70      258000
       71+        162300
진상     20~25       44000
       26~30       89000
       31~35      332000
       36~40      263500
       41~45      396500
       46~50      242000
       51~55      243500
       56~60      110500
       71+         87500
참드림    36~40       73000
추청     17~19       68800
       20~25     1858100
       26~30     5366500
       31~35     5778700
       36~40    11254100
       41~45    12040600
       46~50    12105300
       51~55     8639100
       56~60     5136100
       61~65     2321200
       66~70      730200
       71+        527400
하이아미   31~35      202800
       36~40      783600
       41~45      165300
       46~50      206500
       51~55       82800
       66~70       42000
혼합     14~16       63500
       17~19       10500
       20~25      253200
       26~30      458400
       31~35      510500
       36~40      640300
       41~45     1847900
       46~50     2680900
       51~55     1709300
       56~60      388500
       61~65      253500
       66~70       64500
Name: 실결제금액, dtype: int64

In [25]:
품종별나이_결제금액 = pd.DataFrame(grouped_name_s_r, columns=['실결제금액'])
품종별나이_결제금액

                실결제금액
품종    나이
고시히카리 20~25    445900
      26~30   1735400
      31~35   6060200
      36~40   6765700
      41~45   6814700
      46~50   3606500
      51~55   2830200
      56~60   2276500
      61~65    690500
      66~70     79900
      71+       83800
삼광    20~25    491300
      26~30   1008400
      31~35   1233700
      36~40   2646600
      41~45   2292700
      46~50   1944100
      51~55   1376600
      56~60    744300
      61~65    261000
      66~70    202500
새청무   20~25    120400
      26~30    839300
      31~35    361200
      36~40    120400
      41~45    177600
      46~50    601500
      51~55    120400
      56~60    361200
      61~65    301000
      66~70     60200
      71+       60200
신동진   20~25   1773600
      26~30   2973200
      31~35   5273700
      36~40   9240800
      41~45   7408000
      46~50   9458400
      51~55   4539300
      56~60   2008400
      61~65    751600
      66~70    405100
      71+      126800
십리향   20~25     88200
      26~30    538000
      31~35    731700
      36~40    728400
      41~45    507900
      46~50    486300
      51~55    834900
      56~60    263600
      61~65    133400
      71+       44100
영호진미  20~25    235000
      26~30    818900
      31~35   2397000
      36~40   2226000
      41~45   2430500
      46~50   1178500
      51~55    833500
      56~60    472000
      61~65    214500
      66~70     21000
      71+      264000
오대    26~30     60200
      31~35     60200
      36~40     58200
      41~45    239800
      46~50     80600
      56~60    166600
      61~65     19400
      66~70     43000
일미    26~30     34500
      31~35    149500
      36~40    689100
      41~45    210600
      46~50    180500
      51~55    238700
      56~60     66600
      61~65     72000
      66~70     66600
      71+      263900
일품    20~25    674400
      26~30   1188000
      31~35   1360900
      36~40   2538600
      41~45   3811900
      46~50   2350100
      51~55    849700
      56~60    856000
      61~65    356700
      66~70    258000
      71+      162300
진상    20~25     44000
      26~30     89000
      31~35    332000
      36~40    263500
      41~45    396500
      46~50    242000
      51~55    243500
      56~60    110500
      71+       87500
참드림   36~40     73000
추청    17~19     68800
      20~25   1858100
      26~30   5366500
      31~35   5778700
      36~40  11254100
      41~45  12040600
      46~50  12105300
      51~55   8639100
      56~60   5136100
      61~65   2321200
      66~70    730200
      71+      527400
하이아미  31~35    202800
      36~40    783600
      41~45    165300
      46~50    206500
      51~55     82800
      66~70     42000
혼합    14~16     63500
      17~19     10500
      20~25    253200
      26~30    458400
      31~35    510500
      36~40    640300
      41~45   1847900
      46~50   2680900
      51~55   1709300
      56~60    388500
      61~65    253500
      66~70     64500

In [13]:
품종별나이_결제수량.to_csv('품종나이_결제수량.csv', index=False, sep=' ',encoding='utf8')